### ISSUE TITLE
] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.

### ISSUE THREAD

**Issue by livelyPeng** [SystemLight/create-kiva#1]
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(Use `node --trace-deprecation ...` to show where the warning was created)

这是啥意思 ，能有偿解决下不

**Comment by SystemLight** [comment]
1. webpack5启用了很多方法，Compilation.assets 是制作webpack插件时所需要的实例对象，在webpack4之前很多插件都是使用这个属性的，警告问题可以忽略，未来相应的插件更新后这个问题自然会消失，目前不推荐直接使用webpack5
